### ISSUE TITLE
Required fields in the schema are not being validated

### ISSUE THREAD

**Issue by RafaelAPNascimento** [conqa/serverless-openapi-documentation#25]
In the property **documentation/models/schema** I'm pointing to a JSON schema file of the object supposed to be sent in the request body:

```
models:
    - schema: ${file(models/test.json)}
      name: 'Tester'
      description: 'Esquema Tester Object'
      contentType: 'application/json'
```
Even though I declared some required fields in the schema, the object is sent when those fields are absent. **The request shouldn't be executed successfully under that scenario**.

It works properly if I **also** declare the schema in the serverless.yml (functions/events/Http/request):

```
events:
      - http:
          path: /tester
          method: post
          integration: lambda
          request:
            schema:
              application/json: ${file(models/test.json)}
            template:
              application/json: $input.json('$')
          documentation: ${file(my-project-api.doc.yml):endpoints.tester}
```
 But that configuration is not desirable since I have to set the request schema in **two places**, so the risk to break things in big/complex projects are very high.

_test schema_ with some required fields:
```
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Test",
  "description": "Tester",
  "type": "object",
  "required": [ "age", "name" ],
  "properties": {

    "name": {
      "type": "string",
      "description": "names"
    },
    "age" : {
      "type": "integer",
      "description": "age"
    },
    "is": {
      "type": "boolean",
      "description": "type"
    }
  }
}
```
